# .circleci/config.yml

version: 2.1
orbs:
  node: circleci/node@5
jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - run: echo "installing dependencies..."
      - run: echo "code analysing..."
      - run: echo "cleaning and packaging..."
  tests:
    # Install node dependencies and run test
    executor: node/default
    environment:
      JEST_JUNIT_OUTPUT_DIR: ./test-results/
    steps:
      - checkout
      - run: echo "tests unitaires"
      - run: echo "tests d'intégration"
      - run: echo "tests de régression"
      - run: echo "tests performance"
      - run: echo "tests sécurité"
      - run: echo "tests compatibilité"
      - run: echo "tests accessibilité"
  deploy:
    executor: node/default
    steps:
      - checkout
      - run: echo "Deploying"
  deploy_prod:
    executor: node/default
    steps:
      - checkout
      - run: echo "Deploying to production environment"
workflows:
  build-test-deploy:
    jobs:
      - build
      - tests:
          requires:
            - build
      - deploy:
          requires:
            - tests
          filters:
            branches:
              ignore:
                - /feature\//*/
                - /hotfix\//*/
      - deploy_prod:
          requires:
            - tests
          filters:
            branches:
              only:
                - master
